using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GridManager : MonoBehaviour
{
    private static int tileSize = 5;
    [SerializeField]
    private List<Tile> tileList;
    private static Dictionary<Vector2, Tile> grid;
    [SerializeField]
    private bool isAutoGenerated = false;

    private void Awake()
    {
        grid = new Dictionary<Vector2, Tile>();
    }

    // Start is called before the first frame update
    void Start()
    {
        if (this.isAutoGenerated)
        {

        }
        else if(tileList != null && tileList.Count > 0)
        {
            this.GenerateGridFromExistingTiles();
        }
    }

    private void GenerateGridFromExistingTiles()
    {
        int initialPlanetHealth = 0;
        foreach (Tile tile in this.tileList)
        {
            Vector2 tilePosition = new Vector2(tile.transform.position.x / tileSize, tile.transform.position.z / tileSize);
            initialPlanetHealth += tile.GetComponent<NatureTile>().amountRessourceAvailable;
            grid.Add(tilePosition, tile);
        }
        GameController.SetInitialPlanetHealth(initialPlanetHealth);
    }

    public static void UpdateGridElement(Tile tile)
    {
        Vector2 tilePosition = new Vector2(tile.transform.position.x / tileSize, tile.transform.position.z / tileSize);
        Tile oldTile = grid[tilePosition];
        NatureTile nature = oldTile.GetComponent<NatureTile>();
        GameController.ReducePlanetHealth(nature.amountRessourceAvailable);
        grid[tilePosition] = tile;
    }

}
